services:
  mysql:
    image:                  mysql:latest
    container_name:         mysql-sa
    restart:                always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD:  root
      MYSQL_DATABASE:       whatsapp_db

  adminer:
    image: adminer
    container_name: adminer_whatsapp
    restart: always
    ports:
      - "8000:8080"
    depends_on:
      - mysql
