CREATE TABLE IF NOT EXISTS  Users
(
 id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
 username VARCHAR (30) UNIQUE NOT NULL,
 email VARCHAR (100) UNIQUE NOT NULL,
 full_name VARCHAR (100) ,
 password VARCHAR (255) ,
 country_id BIGINT NOT NULL,
 city_id BIGINT,
 rule_id BIGINT NOT NULL,
 created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 profile VARCHAR(255) ,
 CONSTRAINT user_country_fk foreign key (country_id) REFERENCES Country(id),
 CONSTRAINT user_city_fk FOREIGN KEY (city_id) REFERENCES City(id),
 CONSTRAINT user_rule_fk FOREIGN KEY (rule_id) REFERENCES Rules(id)
);