CREATE TABLE IF NOT EXISTS  Conversations (
id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
sender_id BIGINT NOT NULL ,
dest_id BIGINT NOT NULL,
is_active TINYINT(1) NOT NULL DEFAULT 1,
created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT sender_fk FOREIGN KEY (sender_id) REFERENCES Users(id),
CONSTRAINT dest_fk FOREIGN KEY (dest_id) REFERENCES Users(id)
);