CREATE TABLE IF NOT EXISTS Groupes
(
id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR (100) NOT NULL,
description VARCHAR (500),
profile VARCHAR (255) ,
is_active TINYINT(1) NOT NULL DEFAULT 1,
created_at  TIMESTAMP  DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);