CREATE TABLE IF NOT EXISTS MessageMedias(
      id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
      media VARCHAR (255) NOT NULL,
      message_id BIGINT NOT NULL,
      is_active TINYINT(1) NOT NULL DEFAULT 1,
      created_at  TIMESTAMP  DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      CONSTRAINT message_id_media_fk FOREIGN KEY (message_id) REFERENCES Messages(id) ON DELETE CASCADE
)